# Generated by Django 5.2 on 2025-04-18 12:07

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Mobil',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('merk', models.CharField(max_length=100)),
                ('model', models.CharField(max_length=100)),
                ('tahun', models.IntegerField()),
                ('harga_dasar', models.DecimalField(decimal_places=2, max_digits=15)),
                ('dana_bank', models.DecimalField(blank=True, decimal_places=2, max_digits=15, null=True)),
                ('suku_bunga', models.FloatField(blank=True, null=True)),
            ],
        ),
    ]
