# Generated by Django 5.2 on 2025-04-18 12:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mobil_showroom', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='mobil',
            name='dana_bank',
        ),
        migrations.RemoveField(
            model_name='mobil',
            name='suku_bunga',
        ),
        migrations.AddField(
            model_name='mobil',
            name='pinjaman_dana_bank',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True),
        ),
        migrations.AddField(
            model_name='mobil',
            name='suku_bunga_bank',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=5, null=True),
        ),
        migrations.AlterField(
            model_name='mobil',
            name='harga_dasar',
            field=models.DecimalField(decimal_places=2, max_digits=10),
        ),
    ]
