# Generated by Django 5.2 on 2025-04-18 13:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mobil_showroom', '0003_rename_harga_dasar_mobil_harga_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='mobil',
            name='harga_dasar',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=12),
        ),
        migrations.AddField(
            model_name='mobil',
            name='merk',
            field=models.CharField(default='Merk Default', max_length=100),
        ),
        migrations.AddField(
            model_name='mobil',
            name='model',
            field=models.CharField(default='Model Default', max_length=50),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='mobil',
            name='pinjaman_dana_bank',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=15),
        ),
        migrations.AddField(
            model_name='mobil',
            name='suku_bunga_bank',
            field=models.FloatField(default=5.0),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='mobil',
            name='tahun',
            field=models.IntegerField(default=2020),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='mobil',
            name='harga',
            field=models.DecimalField(decimal_places=2, max_digits=12),
        ),
    ]
