# Generated by Django 5.2 on 2025-04-19 15:19

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mobil_showroom', '0004_mobil_harga_dasar_mobil_merk_mobil_model_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='Service',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('tanggal_service', models.DateField()),
                ('deskripsi', models.TextField()),
                ('biaya', models.DecimalField(decimal_places=2, max_digits=12)),
                ('mobil', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='services', to='mobil_showroom.mobil')),
            ],
        ),
    ]
