# Generated by Django 5.2 on 2025-04-20 04:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mobil_showroom', '0006_alter_mobil_harga_alter_mobil_harga_dasar_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='mobil',
            name='harga',
            field=models.DecimalField(decimal_places=2, max_digits=12),
        ),
        migrations.AlterField(
            model_name='mobil',
            name='harga_dasar',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=12),
        ),
        migrations.AlterField(
            model_name='mobil',
            name='pinjaman_dana_bank',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=15),
        ),
    ]
